/**
 * Estudiantes:
 * Jennifer Ramirez C.I 26.480.892
 * Daniel Mosquera C.I 26.779.308
 * Yovani Navas C.I 26.668.030
 * Alyeluz Perez C.I 21.129.930
 * Samary Vargas C.I 26.835.762
 * 
 */
package vistas;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;
public class View_Gestion_Carrera extends javax.swing.JFrame {

    /**
     * Creates new form View_Gestion_carrera
     */
    public View_Gestion_Carrera() {
        initComponents();
        
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblgestion_carr = new javax.swing.JLabel();
        lblcodigo_carr = new javax.swing.JLabel();
        lblnombre_carr = new javax.swing.JLabel();
        btn_limpiar_carrera = new javax.swing.JButton();
        btn_buscar_carrera = new javax.swing.JButton();
        btn_eliminar_carrera = new javax.swing.JButton();
        txt_codigo_carrera = new javax.swing.JTextField();
        txt_nombre_carrera = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_carrera = new javax.swing.JTable();
        btn_agregar_carrera = new javax.swing.JButton();
        btn_modificar_carrera = new javax.swing.JButton();
        lblnombre_carr2 = new javax.swing.JLabel();
        txt_nombre_carr2 = new javax.swing.JTextField();
        combo_box_asigna = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblgestion_carr.setText("Gestion Carrera");

        lblcodigo_carr.setText("Codigo");

        lblnombre_carr.setText("Nombre");

        btn_limpiar_carrera.setText("Limpiar");

        btn_buscar_carrera.setText("Buscar");
        btn_buscar_carrera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscar_carreraActionPerformed(evt);
            }
        });

        btn_eliminar_carrera.setText("Eliminar");

        table_carrera.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo Carrera", "Nombre", "Nombre Asignatura", "Código Estudiante", "Nombres", "Apellidos"
            }
        ));
        table_carrera.setDropMode(javax.swing.DropMode.INSERT_ROWS);
        table_carrera.setShowGrid(true);
        jScrollPane1.setViewportView(table_carrera);

        btn_agregar_carrera.setText("Agregar");

        btn_modificar_carrera.setText("Modificar");
        btn_modificar_carrera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_modificar_carreraActionPerformed(evt);
            }
        });

        lblnombre_carr2.setText("Codigo Estudiante");

        combo_box_asigna.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Seleccione Asignaturas-", "Programación III", "Programacón Numérica", "Sistemas II", "Estructuras Discretas II", "Estaditica II" }));
        combo_box_asigna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_box_asignaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblcodigo_carr)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_codigo_carrera, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_buscar_carrera))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(combo_box_asigna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(74, 74, 74)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(lblnombre_carr)
                        .addGap(42, 42, 42))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                        .addComponent(lblnombre_carr2)
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_nombre_carr2, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_nombre_carrera, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(263, 263, 263))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(btn_limpiar_carrera)
                        .addGap(63, 63, 63)
                        .addComponent(btn_agregar_carrera)
                        .addGap(48, 48, 48)
                        .addComponent(btn_modificar_carrera)
                        .addGap(84, 84, 84)
                        .addComponent(btn_eliminar_carrera))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 844, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(388, 388, 388)
                        .addComponent(lblgestion_carr)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(lblgestion_carr)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblcodigo_carr)
                    .addComponent(lblnombre_carr)
                    .addComponent(txt_codigo_carrera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_nombre_carrera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_buscar_carrera))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblnombre_carr2)
                    .addComponent(txt_nombre_carr2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(combo_box_asigna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_agregar_carrera)
                    .addComponent(btn_limpiar_carrera)
                    .addComponent(btn_eliminar_carrera)
                    .addComponent(btn_modificar_carrera))
                .addGap(61, 61, 61))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_buscar_carreraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscar_carreraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_buscar_carreraActionPerformed

    private void btn_modificar_carreraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_modificar_carreraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_modificar_carreraActionPerformed

    private void combo_box_asignaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_box_asignaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combo_box_asignaActionPerformed

    public JButton getBtn_agregar_carrera() {
        return btn_agregar_carrera;
    }

    public void setBtn_agregar_carrera(JButton btn_agregar_carrera) {
        this.btn_agregar_carrera = btn_agregar_carrera;
    }

    public JButton getBtn_buscar_carrera() {
        return btn_buscar_carrera;
    }

    public void setBtn_buscar_carrera(JButton btn_buscar_carrera) {
        this.btn_buscar_carrera = btn_buscar_carrera;
    }

    public JButton getBtn_eliminar_carrera() {
        return btn_eliminar_carrera;
    }

    public void setBtn_eliminar_carrera(JButton btn_eliminar_carrera) {
        this.btn_eliminar_carrera = btn_eliminar_carrera;
    }

    public JButton getBtn_limpiar_carrera() {
        return btn_limpiar_carrera;
    }

    public void setBtn_limpiar_carrera(JButton btn_limpiar_carrera) {
        this.btn_limpiar_carrera = btn_limpiar_carrera;
    }

    public JButton getBtn_modificar_carrera() {
        return btn_modificar_carrera;
    }

    public void setBtn_modificar_carrera(JButton btn_modificar_carrera) {
        this.btn_modificar_carrera = btn_modificar_carrera;
    }

    public JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    public void setjScrollPane1(JScrollPane jScrollPane1) {
        this.jScrollPane1 = jScrollPane1;
    }

    public JLabel getLblcodigo_carr() {
        return lblcodigo_carr;
    }

    public void setLblcodigo_carr(JLabel lblcodigo_carr) {
        this.lblcodigo_carr = lblcodigo_carr;
    }

    public JLabel getLblgestion_carr() {
        return lblgestion_carr;
    }

    public void setLblgestion_carr(JLabel lblgestion_carr) {
        this.lblgestion_carr = lblgestion_carr;
    }

    public JLabel getLblnombre_carr() {
        return lblnombre_carr;
    }

    public void setLblnombre_carr(JLabel lblnombre_carr) {
        this.lblnombre_carr = lblnombre_carr;
    }

    public JTable getTable_carrera() {
        return table_carrera;
    }

    public void setTable_carrera(JTable table_carrera) {
        this.table_carrera = table_carrera;
    }

    public JTextField getTxt_codigo_carrera() {
        return txt_codigo_carrera;
    }

    public void setTxt_codigo_carrera(JTextField txt_codigo_carrera) {
        this.txt_codigo_carrera = txt_codigo_carrera;
    }

    public JTextField getTxt_nombre_carrera() {
        return txt_nombre_carrera;
    }

    public void setTxt_nombre_carrera(JTextField txt_nombre_carrera) {
        this.txt_nombre_carrera = txt_nombre_carrera;
    }

   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btn_agregar_carrera;
    public javax.swing.JButton btn_buscar_carrera;
    public javax.swing.JButton btn_eliminar_carrera;
    public javax.swing.JButton btn_limpiar_carrera;
    public javax.swing.JButton btn_modificar_carrera;
    public javax.swing.JComboBox<String> combo_box_asigna;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JLabel lblcodigo_carr;
    public javax.swing.JLabel lblgestion_carr;
    public javax.swing.JLabel lblnombre_carr;
    public javax.swing.JLabel lblnombre_carr2;
    public javax.swing.JTable table_carrera;
    public javax.swing.JTextField txt_codigo_carrera;
    public javax.swing.JTextField txt_nombre_carr2;
    public javax.swing.JTextField txt_nombre_carrera;
    // End of variables declaration//GEN-END:variables
}
