
/*
 *      Integrantes:
 *          Mosquera, Daniel   C.I: 26.779.308
 *          Navas, Yovani      C.I: 26.668.030
 *          Perez, Alyeluz     C.I: 21.129.930
 *          Ramirez, Jennifer  C.I: 26.480.892
 *          Vargas, Samary     C.I: 26.835.762
 */

package vistas;




public class View_Menu extends javax.swing.JFrame {
    

    /**
     * Creates new form Views_Menu
     */
  
    public View_Menu() {
        initComponents();
        //ubica el JFrame en el centro de la pantalla
        setLocationRelativeTo(null);
        //muestra el Jframe
        setVisible(true);
        //dimensionar la vista
        //el tamaño de la vista se adapta a la pantalla a
        this.setExtendedState(this.MAXIMIZED_BOTH);
        this.setTitle("Sistema de gestión académica");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenu18 = new javax.swing.JMenu();
        jMenu24 = new javax.swing.JMenu();
        jToggleButton1 = new javax.swing.JToggleButton();
        jMenuItem5 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btn_inscripcion = new javax.swing.JButton();
        btn_estudiantes = new javax.swing.JButton();
        btn_profesores = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu6 = new javax.swing.JMenu();
        jMenu22 = new javax.swing.JMenu();
        jMenu13 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu6Inscripcion = new javax.swing.JMenu();
        jmi_Inscribir = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenu12 = new javax.swing.JMenu();
        jmi_registrarestu = new javax.swing.JMenuItem();
        jMenu15 = new javax.swing.JMenu();
        jmi_registrarprofe = new javax.swing.JMenuItem();
        jMenu10 = new javax.swing.JMenu();

        jMenu1.setText("jMenu1");

        jMenu2.setText("jMenu2");

        jMenuItem1.setText("jMenuItem1");

        jMenu3.setText("jMenu3");

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        jMenuItem3.setText("jMenuItem3");

        jMenuItem4.setText("jMenuItem4");

        jMenu4.setText("jMenu4");

        jMenu18.setText("jMenu18");

        jMenu24.setText("jMenu24");

        jToggleButton1.setText("jToggleButton1");

        jMenuItem5.setText("jMenuItem5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(177, 240, 221));

        jLabel7.setFont(new java.awt.Font("Roboto", 3, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(13, 72, 54));
        jLabel7.setText("Universidad Central de Lara");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes_Vistas/logo universidad.png"))); // NOI18N

        btn_inscripcion.setText("Inscribir estudiante");

        btn_estudiantes.setText("Gestion estudiantes");

        btn_profesores.setText("Gestion profesores");

        jLabel1.setText("Botones funcionables");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_inscripcion)
                    .addComponent(jLabel2))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(btn_estudiantes)
                        .addGap(30, 30, 30)
                        .addComponent(btn_profesores))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel7))))
                .addContainerGap(550, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_inscripcion)
                    .addComponent(btn_estudiantes)
                    .addComponent(btn_profesores))
                .addGap(121, 121, 121)
                .addComponent(jLabel7)
                .addContainerGap(149, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(118, 118, 118))
        );

        jMenuBar2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(13, 72, 54), 2, true));
        jMenuBar2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N

        jMenu6.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(21, 93, 106)));
        jMenu6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes_Vistas/icons8-class-36.png"))); // NOI18N
        jMenu6.setText("Asignatura");
        jMenu6.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jMenu6.setPreferredSize(new java.awt.Dimension(100, 50));

        jMenu22.setText("Retiro");
        jMenu22.setPreferredSize(new java.awt.Dimension(200, 30));
        jMenu6.add(jMenu22);

        jMenu13.setText("Gestionar Asignaturas");
        jMenu13.setPreferredSize(new java.awt.Dimension(200, 30));
        jMenu6.add(jMenu13);

        jMenuBar2.add(jMenu6);

        jMenu5.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(21, 93, 106)));
        jMenu5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes_Vistas/icons8-group-32.png"))); // NOI18N
        jMenu5.setText("Sección");
        jMenu5.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jMenu5.setPreferredSize(new java.awt.Dimension(100, 50));

        jMenuItem2.setText("Gestionar Secciones");
        jMenu5.add(jMenuItem2);

        jMenuBar2.add(jMenu5);

        jMenu6Inscripcion.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(21, 93, 106)));
        jMenu6Inscripcion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes_Vistas/icons8-document-36.png"))); // NOI18N
        jMenu6Inscripcion.setText("Inscripción");
        jMenu6Inscripcion.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jMenu6Inscripcion.setPreferredSize(new java.awt.Dimension(100, 50));

        jmi_Inscribir.setText("Inscribir Estudiante");
        jmi_Inscribir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_InscribirActionPerformed(evt);
            }
        });
        jMenu6Inscripcion.add(jmi_Inscribir);

        jMenuBar2.add(jMenu6Inscripcion);

        jMenu8.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(21, 93, 106)));
        jMenu8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes_Vistas/icons8-exam-32.png"))); // NOI18N
        jMenu8.setText("Cargar Notas");
        jMenu8.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jMenu8.setPreferredSize(new java.awt.Dimension(170, 50));
        jMenuBar2.add(jMenu8);

        jMenu7.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(21, 93, 106)));
        jMenu7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes_Vistas/icons8-report-32.png"))); // NOI18N
        jMenu7.setText("Reportes");
        jMenu7.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jMenu7.setPreferredSize(new java.awt.Dimension(150, 50));

        jMenuItem9.setText("Lista de Promedio por Sección");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem9);

        jMenuItem8.setText("Listado de Estudiantes con mayor promedio ");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem8);

        jMenuItem10.setText("Listado de Estudiantes con menor promedio");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem10);

        jMenuItem11.setText("Listado de Estudiantes por Carrera");
        jMenu7.add(jMenuItem11);

        jMenuItem12.setText("Listado de Estudiantes por Semestre");
        jMenu7.add(jMenuItem12);

        jMenuItem13.setText("Listado de Estudiantes por Genero y Decanato");
        jMenu7.add(jMenuItem13);

        jMenuItem7.setText("Listado de Estudiantes con mejores promedio por Decanato");
        jMenu7.add(jMenuItem7);

        jMenuItem14.setText("Listado de Estudiantes con promedio por encima por Seccion y Carrera");
        jMenu7.add(jMenuItem14);

        jMenuBar2.add(jMenu7);

        jMenu12.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(21, 93, 106)));
        jMenu12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes_Vistas/icons8-student-32.png"))); // NOI18N
        jMenu12.setText("Estudiante");
        jMenu12.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jMenu12.setMaximumSize(new java.awt.Dimension(120, 32767));
        jMenu12.setPreferredSize(new java.awt.Dimension(150, 50));

        jmi_registrarestu.setText("Registrar Estudiante");
        jMenu12.add(jmi_registrarestu);

        jMenuBar2.add(jMenu12);

        jMenu15.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(21, 93, 106)));
        jMenu15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes_Vistas/icons8-teacher-32.png"))); // NOI18N
        jMenu15.setText("Profesor");
        jMenu15.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jMenu15.setMaximumSize(new java.awt.Dimension(120, 32767));
        jMenu15.setPreferredSize(new java.awt.Dimension(150, 50));

        jmi_registrarprofe.setText("Registrar profesor");
        jMenu15.add(jmi_registrarprofe);

        jMenuBar2.add(jMenu15);

        jMenu10.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(21, 93, 106)));
        jMenu10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes_Vistas/icons8-log-out-32.png"))); // NOI18N
        jMenu10.setText("Cerrar Sesión");
        jMenu10.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jMenu10.setPreferredSize(new java.awt.Dimension(150, 50));
        jMenuBar2.add(jMenu10);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jmi_InscribirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_InscribirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmi_InscribirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(View_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(View_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(View_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(View_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new View_Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btn_estudiantes;
    public javax.swing.JButton btn_inscripcion;
    public javax.swing.JButton btn_profesores;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu1;
    public javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu12;
    private javax.swing.JMenu jMenu13;
    private javax.swing.JMenu jMenu15;
    private javax.swing.JMenu jMenu18;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu22;
    private javax.swing.JMenu jMenu24;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    public javax.swing.JMenu jMenu5;
    public javax.swing.JMenu jMenu6;
    public javax.swing.JMenu jMenu6Inscripcion;
    public javax.swing.JMenu jMenu7;
    public javax.swing.JMenu jMenu8;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToggleButton jToggleButton1;
    public javax.swing.JMenuItem jmi_Inscribir;
    public javax.swing.JMenuItem jmi_registrarestu;
    public javax.swing.JMenuItem jmi_registrarprofe;
    // End of variables declaration//GEN-END:variables
}
